set(CPACK_PACKAGE_VENDOR ${MOSAIQ_VENDOR})
set(CPACK_PACKAGE_CONTACT ${MOSAIQ_CONTACT})
set(CPACK_DEBIAN_PACKAGE_MAINTAINER ${CPACK_PACKAGE_VENDOR})
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
IF(DEFINED ENV{MOSAIQ_BUILD_NUMBER})
    set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}-build$ENV{MOSAIQ_BUILD_NUMBER}")  
ELSE()
    set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
ENDIF()
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "${MOSAIQ_PROJECT_DEB_DEPENDENCIES}")


set(SOURCE_PACKAGE_GENERATORS "")

option(PACKAGE_TGZ "Use package generator for TGZ" FALSE)
if(PACKAGE_TGZ)
    list(APPEND SOURCE_PACKAGE_GENERATORS "TGZ")
endif()

option(PACKAGE_STGZ "Use package generator for STGZ" FALSE)
if(PACKAGE_STGZ)
    list(APPEND SOURCE_PACKAGE_GENERATORS "STGZ")
endif()

option(PACKAGE_TBZ2 "Use package generator for TBZ2" FALSE)
if(ENABLE_TBZ2)
    list(APPEND SOURCE_PACKAGE_GENERATORS "TBZ2")
endif()

option(PACKAGE_TZ "Use package generator for TZ" FALSE)
if(PACKAGE_TZ)
    list(APPEND SOURCE_PACKAGE_GENERATORS "TZ")
endif()

option(PACKAGE_ZIP "Use package generator for ZIP" FALSE)
if(PACKAGE_ZIP)
    list(APPEND SOURCE_PACKAGE_GENERATORS "ZIP")
endif()

set(CPACK_SOURCE_GENERATOR ${SOURCE_PACKAGE_GENERATORS})
set(CPACK_SOURCE_IGNORE_FILES
    /.gitignore
    /.git
    /dist
    /.*build.*
    /\\\\.DS_Store
)

set(PACKAGE_GENERATORS "")

option(PACKAGE_DEB "Use package generator for DEB" TRUE)
if(PACKAGE_DEB)
    list(APPEND PACKAGE_GENERATORS "DEB")
endif()

set(CPACK_GENERATOR ${PACKAGE_GENERATORS})

include(CPack)
